In [18]:
%load_ext autoreload
%autoreload 2
import numpy as np
from diagram_sampler import ZX_diag_sampler

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [30]:
seed = 0

size_fac = 100

n_in_min = 1 * size_fac
n_in_max = 3 * size_fac
min_spiders = 10 * size_fac
max_spiders = 50 * size_fac
pi_fac = 0.5
pi_half_fac = 0.5
arb_fac = 0.5
p_hada = 0.2
min_mean_neighbours = 2
max_mean_neighbours = 4
remove_disconnected = True
rng = np.random.default_rng(seed)

diag_sampler = ZX_diag_sampler(n_in_min, n_in_max, min_spiders, max_spiders, 
                               pi_fac, pi_half_fac, arb_fac, p_hada, min_mean_neighbours, 
                               max_mean_neighbours, remove_disconnected, rng)

In [31]:
diag_sampler.sample()

(array([[0, 0, 0, 1, 0],
        [0, 0, 0, 1, 0],
        [0, 0, 0, 1, 0],
        ...,
        [0, 0, 1, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 1, 0, 0]]),
 array([[0, 0, 0, 0, 1],
        [0, 0, 0, 0, 1],
        [0, 0, 0, 0, 1],
        ...,
        [0, 0, 0, 0, 1],
        [0, 0, 0, 0, 1],
        [0, 0, 0, 0, 1]]),
 array([   0,    1,    2, ..., 2088, 1778, 2061]),
 array([ 498,  499,  500, ..., 3268, 3269, 3269]))

In [32]:
samples = 10000
for _ in range(samples):
    diag_sampler.sample()